### ISSUE TITLE
How to show custom tag field data on each node instead of showing node id

### ISSUE THREAD

**Issue by UmerTaptap** [graph-cn/flutter_graph_view#17]

**Comment by CorvusYe** [comment]
Could you try options.textGetter ？

**Comment by UmerTaptap** [comment]
> Could you try options.textGetter ？

Ahhh thanks man ❤️

**Comment by CorvusYe** [comment]
You're welcome. Have fun.  ⭐️❤️

**Comment by UmerTaptap** [comment]
one more question please, how can i change text color? currently it is giving random colors for each node and vertexes.

**Comment by CorvusYe** [comment]
But now, the color of the line depends on the first and last nodes. Unless you change the default EdgeShape.
