### ISSUE TITLE
When i zoom in and out, the distance between node changes, is there any way i can zoom in and out only nodes? like i want to see picture in my custom vertex, when i zoom in to see the picture, then picture node/vertex size remains same only the distance between nodes chnages....

### ISSUE THREAD

**Issue by UmerTaptap** [graph-cn/flutter_graph_view#19]

**Comment by CorvusYe** [comment]
Maybe you can create a custom node decorator and get the scaling ratio inside it, instead of using a fixed value like here. 

https://github.com/graph-cn/flutter_graph_view/blob/main/lib/core/options/shape/vertex/vertex_decorator.dart#L34-L34


However, I might prefer to use a panel to preview the image. Of course, this depends on actual needs.

**Comment by UmerTaptap** [comment]
Ahh got it, Thanks dude ❤️
One more question, I want to center the specific node when user opens the app, I mean I have family tree type structure and I want to zoomed my/self node when I open the app, how can I achieve this?

**Comment by CorvusYe** [comment]
Write a decorator to add to the layout algorithm that can specify a specific node to center. The logic for specifying which node can be placed in the decorator.

**Comment by UmerTaptap** [comment]
`class CenterSpecificDecoder extends GraphAlgorithm {
  final String? specificNodeId;

  CenterSpecificDecoder({this.specificNodeId});

  @override
  void onLoad(Vertex v) {
    super.onLoad(v);
    if (specificNodeId != null && v.id == specificNodeId) {
      v.cpn?.graphComponent?. 
    }
  }
}`

Could you please help me completing this?

**Comment by CorvusYe** [comment]
@UmerTaptap 
You can try it, there may be some minor issues and unnecessary double counting. 
But if your data volume is not large, there shouldn't be any problem.

```dart

import '../../../flutter_graph_view.dart';

class CenterSpecificDecoder extends GraphAlgorithm {
  final String? specificNodeId;

  CenterSpecificDecoder({this.specificNodeId});

  @override
  void compute(Vertex v, Graph graph) {
    super.compute(v, graph);
    if (pinCenter(v)) {
      v.position = (v.cpn?.game.size ?? Vector2.zero()) / 2;
    }
  }

  bool pinCenter(Vertex v) {
    return specificNodeId == v.id;
  }
}
```
