### ISSUE TITLE
Are you planning to add developer-control over the length of edges?

### ISSUE THREAD

**Issue by muknta** [graph-cn/flutter_graph_view#7]
Thanks for your amazing work!
We need something like this for our work. It looks like relations graph with controllable distance from the center

Are you planning to do this? Or, at least, your suggestions would be helpful regarding some changes I should make in the example code / library interface
<img width="761" alt="image" src="https://github.com/graph-cn/flutter_graph_view/assets/31825654/c73f1f86-948f-4362-b211-362830cba281">

P.S. it could be even static, without node movements

**Comment by CorvusYe** [comment]
The length of the line depends on the position of the head and tail nodes.
Maybe you can implement the GraphAlgorithm like this. https://github.com/graph-cn/flutter_graph_view/blob/main/example/lib/algorithm/random_algorithm.dart#L10-L10

**Comment by CorvusYe** [comment]
Then configure the custom positioning algorithm here.
​https://github.com/graph-cn/flutter_graph_view/blob/main/example/lib/main.dart#L56-L56

**Comment by CorvusYe** [comment]
To implement this method, the timing of the calculation will be earlier, if you want to assist multiple points at the same time.
​
​https://github.com/graph-cn/flutter_graph_view/blob/main/examples/execution_plan/lib/src/flow_layout.dart#L44-L44

**Comment by muknta** [comment]
@CorvusYe thanks for your suggestions. I got result after editing the ForceDirected algorithm and MapConvertor with using the `deep` var.
Thanks!

ForceDirected2 is causing infinity error, btw

**Comment by CorvusYe** [comment]
Thanks for the feedback. The force-oriented graph algorithm has not yet been consistent with the laws of physics, and I am still trying to figure out what to do with it.

**Comment by CorvusYe** [comment]
I forgot to mention it. The current version does not support line display yet, when the start node and end node are the same. If you also have such a scenario, you may need to implement another `EdgeShape` interface.

**Comment by muknta** [comment]
Okay, I will look into as far as I integrate this into our app.
But I am not sure what are you about, because the edge line is normally visible and functional
<img width="682" alt="image" src="https://github.com/graph-cn/flutter_graph_view/assets/31825654/a2e4bd5e-3874-4f2d-9748-ab97cf2b1844">

**Comment by CorvusYe** [comment]
The meaning I want to express is as follows:
![image](https://github.com/graph-cn/flutter_graph_view/assets/15630211/d0361580-7416-4227-9cf3-cf303fa685a4)
